version: "3.7"

services:
  zynomi-ui-web:
    networks:
      - frontend
    image: zynomi/zynomi-ui-web:latest
    container_name: zynomi-ui-web
    restart: unless-stopped
    tty: true
    ports:
      - "5000:80"
    environment:
      - REST_ENDPOINT="http://localhost:8000/api"
      - API_KEY=
networks:
  frontend: null
