name: build docker image

on:
  push:
    tags-ignore:
    - '**'
    branches:
    - main
    
env:
  project: 'zynomi-ui-web'
  NAME   : 'zynomi/zynomi-ui-web'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Another step
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "Sha: ${{ steps.vars.outputs.sha_short }}"

      #- name: Build and push
       # uses: docker/build-push-action@v2
        #with:
         # context: .
          #platforms: linux/amd64,linux/arm64,linux/arm/v7
          #push: true
          #tags: latest,${{ steps.vars.outputs.sha_short }}
          ##tags: ${{ secrets.DOCKERHUB_USERNAME }}/ranking:${{ steps.vars.outputs.tag }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{env.NAME}}
          tags: latest,${{ steps.vars.outputs.sha_short }}